### ISSUE TITLE
Class files not included by plugin::Registerclass() using the example src or traditional inc folders

### ISSUE THREAD

**Issue by DonutsNL** [pluginsGLPI/example#42]
Hi,

The plugin::Registerclass() is not able to locate the /ticketfilter/src/Filter.php file and is therefor not included and resolvable/callable from the hook. This works as intended when manually including the class file. I am using the example as provided (Example::class). 

My folder structure:
GLPI_ROOT\marketplace\ticketfilter\
GLPI_ROOT\marketplace\ticketfilter\src

\setup.php

```

use Glpi\Plugin\Hooks; #resolved correctly by VS.
use GlpiPlugin\TicketFilter\Filter; #resolved correctly by VS

function plugin_init_ticketfilter() : void {
    global $PLUGIN_HOOKS;
    Plugin::registerClass(Filter::class);
    // Work around.
    if(!class_exists(Filter::class)){
      $include = pathinfo(__file__)["dirname"]."/src/Filter.php";
      require_once($include);
   }
   $PLUGIN_HOOKS['csrf_compliant']["ticketfilter"] = true;
   
   $PLUGIN_HOOKS[HOOKS::PRE_ITEM_ADD]["ticketfilter"] = [
      Ticket::class       => [Filter::class, "PreItemAdd"]
   ];

```
\src\Filter.php
```
namespace GlpiPlugin\TicketFilter;
use Ticket;
class Filter {
    
    /**
     * Method called by pre_item_add hook validates the object and passes
     * it to the RegEx Matching.
     * 
     * @param $item       Expects the Ticket object by refference.
     * @return void  
     * @since           1.0.0             
     */
    public static function PreItemAdd(Ticket $item) : void {
        if(is_object($item)){
            // Validate if there is a subject to match
            if(is_array($item->fields) 
               && key_exists('name', $item->fields) 
               && !empty($item->fields['name'])) {
               
                // TODO: Do something with debuglogging;
                // if(Config::Debug) { $this->log(); }
                
                $subject = $item->input['name'];
                $matchString = '/.*?(?<remoteId>\(CITI-[0-9]{1,4}\)).+/';
                self::Match($matchString, $subject);
            } // else ignore call
        } // else ignore call
    }
```

As far as I can tell it is following the naming conventions from the examples. Running debug the autoloader ends up not including the file. I tried adding the Plugin::registerClass(Filter::class); with the same result. I also was examples where the src class was named name.class.php i tried that approach without result. Also tried moving the plugin to the plugins folder without result.

What is going wrong in this approach?

**Comment by cconard96** [comment]
Make sure you are on GLPI 10 for improved namespace support.
For this specific issue, your namespace is not correct.
The plugin name part needs to be all lowercase except the first letter.
The full class name should be `GlpiPlugin\Ticketfilter\Filter`.

Also, for clarification, namespaced classes in the core and plugins are not handled by the autoloader in `autoload.function.php`. Instead, they are handled by a Composer autoloader.

**Comment by DonutsNL** [comment]
@cconard96 that worked out great. Thank you for clarifying this convention. Documenting the convention used will prove to be very valuable.

Best everyone updates to the latest GLPI  ;-)

**Comment by DonutsNL** [comment]
Issue fixed

**Comment by cconard96** [comment]
The documentation update regarding this is a WIP:
https://github.com/glpi-project/docdev/pull/139

It even slipped my mind originally that the namespace was case sensitive. I'll have to fix that in the documentation PR.
