### ISSUE TITLE
Include plugin 'vendors' namespaces in GLPI autoloader  

### ISSUE THREAD

**Issue by DonutsNL** [pluginsGLPI/example#49]
I would like to use composer to get and maintain 3rd party libs into the plugin tree and i was wondering. Is there a nice way to extend the GLPI autoloader to include these packages and their namespaces so we can access them using the USE keyword?

**Comment by cedric-anne** [comment]
Hi,

You could do it in the setup file of you plugin.

1. Check that the composer autoloader file exists in the `check_prerequisites()` function:
```php
function plugin_XXX_check_prerequisites()
{
    if (!is_readable(__DIR__ . '/vendor/autoload.php') || !is_file(__DIR__ . '/vendor/autoload.php')) {
        echo "Run composer install --no-dev in the plugin directory<br>";
        return false;
    }

    return true;
}
```

2. Include the composer autoloader file in the `init()` function:
```php
function plugin_init_XXX()
{
    include_once(__DIR__ . '/vendor/autoload.php');
}
```
