### ISSUE TITLE
Don't work on 0.90.5

### ISSUE THREAD

**Issue by ymolinet** [pluginsGLPI/example#7]
Fatal error: Call to undefined method Link::registerTag() in /var/www/plugins/example/setup.php on line 64

**Comment by btry** [comment]
Hi

I created a quick fix here https://github.com/btry/example/tree/master%2Bfix_%C3%ACssue_7

You're welcome to test it.

**Comment by ymolinet** [comment]
it seems to work. thanks.

**Comment by trasher** [comment]
@btry would you open a PR against this ticket please?
